name: Scrape latest data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          cli: 'latest'
      - name: Run scraping
        run: make run
      - name: Commit and push scraped data
        run: |-
          git config user.name "Github Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Automatic scraping at: ${timestamp}" || exit 0
          git push
      - name: Upload CSV to Google Spreadsheet
        uses: canonical-web-and-design/csv-to-google-spreadsheet@1.0.0
        with:
          csv_path: ./bamf-locations.csv
          spreadsheet_id: ${{ secrets.google_spreadsheet_id }}
          worksheet: 0
          google_service_account_email: ${{ secrets.google_service_account_email }}
          google_service_account_private_key: ${{ secrets.google_service_account_private_key }}
